# Define the common configuration
x-common: &common
  environment:
    - USER=${USER}
    - PASSWORD=${DOCKER_PASSWORD:-none} # Use environment variable or default
    - D8Z_PROJECT=env
    - DISPLAY=:1
    - RESOLUTION=2500x1500             # Desktop monitor
#    - RESOLUTION=1920x1080             # Desktop monitor
#    - RESOLUTION=1500x800               # Laptop monitor
  volumes:
    - .:/home/${USER}/projects/env # Mount ourselves to fix ourselves.
    - /var/run/docker.sock:/var/run/docker.sock # Share Docker socket dind
  shm_size: "2g"

services:
  # Base container - builds the base image
  base:
    image: env:base
    container_name: base
    build:
      context: ./base
      args:
        USERNAME: ${USER}
        PASSWORD: ${DOCKER_PASSWORD:-none}
    <<: *common # Inherit common configurations
    networks:
      - internal_net

  # Bazel container
  bazel:
    image: env:bazel
    container_name: bazel
    build:
      context: ./bazel
    <<: *common # Inherit common configurations
    networks:
      - internal_net

  # Docker-in-Docker container
  dind:
    image: env:dind
    container_name: dind
    build:
      context: ./dind
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Share Docker socket
    <<: *common # Inherit common configurations
    networks:
      - internal_net

  # Github container
  github:
    image: env:github
    container_name: github
    build:
      context: .
      dockerfile: ./github/Dockerfile
    environment:
      - GITHUB_TOKEN=${GIT_D8Z_TOKEN:-none}
      - GITHUB_USER=${USER}
      - GITHUB_ORG=${USER}
      - GITHUB_REPO=d8z-cloud-env
    <<: *common # Inherit common configurations
    networks:
      - external_net

  # Voideditor container - VNC enabled editor
  voideditor:
    image: env:voideditor
    container_name: voideditor
    build:
      context: ./voideditor
      args:
        USERNAME: ${USER}
        PASSWORD: ${DOCKER_PASSWORD:-none}
    <<: *common # Inherit common configurations
#    ports:
#      - "80:80"
#      - "6080:80" # Web VNC
#      - "5900:5900" # VNC client
    networks:
      - internal_net
      - external_net

  vscode:
    image: vscode
    container_name: vscode
    build:
      context: ./vscode
      args:
        USERNAME: ${USER}
        PASSWORD: ${DOCKER_PASSWORD}
    #privileged: true
    #ports:
    #  - 8080:8080  # Access: http://localhost:8080
    <<: *common
    # volumes:
      # TODO: Change user from coder to ${USER}.
      # - /tmp/.X11-unix:/tmp/.X11-unix
      # - ./data:/home/${USER}/projects
    networks:
      - internal_net
      - external_net


  # Ollama service
  ollama:
    # image: env:ollama # Optionally tag the image built by compose
    container_name: ollama
    build:
      context: ./ollama
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    #ports:
    # - "80:80"     # Dashboard
    # - "8080:8080" # Reverse Proxy port
    # - "8081:8081" # Forward Proxy port
    <<: *common # Inherit common configurations
    networks:
      internal_net:
        aliases:
          - 127.0.0.1
      external_net: {}

  # Proxy service
  proxy:
    # image: env:proxy # Optionally tag the image built by compose
    container_name: proxy_app
    build:
      context: ./proxy
    ports:
      - "80:80"     # Dashboard
    <<: *common # Inherit common configurations
    networks:
      internal_net:
      #  aliases:
      #    - api.openai.com
      external_net: {}

networks:
  internal_net:
    internal: true
  external_net:
    driver: bridge

