#
# FILE: ~/docker/env/base/bash_aliases

# Source this file.
alias sc='source ~/.bashrc'

# Development tools.
alias emacs='emacs -nw'
alias doughznutz='su doughznutz -p'
alias pasty='xsel --clipboard --output'
alias term='lxterminal --geometry=120x50'
