# https://docs.continue.dev/reference
name: d8z-env
version: 0.0.1
schema: v1

models:
  - name: GPT-4o
    provider: openai
    apiBase: http://ollama:11434/v1
    model: gpt-4o
    roles:
      - chat
      - edit
      - apply
    defaultCompletionOptions:
      temperature: 0.7
      maxTokens: 1500

  - name: My Model - OpenAI-Compatible
    provider: openai
    apiBase: http://ollama:11434/v1
    model: gemini-2.0-flash
    capabilities:
      - tool_use
      - image_input
    roles:
      - chat
      - edit
      - apply

