# https://docs.continue.dev/reference
name: d8z-env
version: 0.0.1
schema: v1

models:
  - name: Gemini
    provider: openai
    apiBase: http://ollama:11434/v1
    model: gemini-2.0-flash
    capabilities:
      - tool_use
      - image_input
    roles:
      - chat
      - edit
      - apply

  - name: GPT
    provider: openai
    apiBase: http://ollama:11434/v1
    model: gpt-4o
    roles:
      - chat
      - edit
      - apply
    defaultCompletionOptions:
      temperature: 0.7
      maxTokens: 1500

  - name: Groq
    provider: openai
    apiBase: http://ollama:11434/v1
    model: llama-3.3-70b-versatile
    roles:
      - chat
      - edit
      - apply

#  - name: Ollama
#    provider: ollama
#    apiBase: http://ollama:11434/v1
#    model: ollama # Change the ollama server to insert model name.
