# FILE: docker/env/github/Dockerfile

# Use doughznutz base ubuntu-nvc image
FROM env:base

# Set environment variables for Git
ENV GIT_AUTHOR_NAME="Doug Hogberg" \
    GIT_AUTHOR_EMAIL="doughznutz@gmail.com" \
    GIT_COMMITTER_NAME="Doug Hogberg" \
    GIT_COMMITTER_EMAIL="doughznutz@gmail.com"

# Override this environment in projects.
ENV GIT_REPO=doughznutz/desktop-tutorial

# Install Git tools
RUN apt-get update && apt-get install -y \
    git \
    git-lfs \
    && apt-get clean

# Install github CLI for easier access
RUN mkdir -p -m 755 /etc/apt/keyrings \
    && out=$(mktemp) \
    && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg \
    && cat $out \
    | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null
RUN chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" \
    | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
RUN apt update && apt install gh -y

# Setup git and lfs
RUN git init
#RUN git lfs install --force

# Consider doing gh_auth here rather than inside the container.

# Copy this directory into the container.
COPY . env/

# Update github aliases
COPY ./bash_aliases bash_aliases
RUN cat bash_aliases >> ~root/.bash_aliases && rm bash_aliases

# Entrypoint for the container
COPY *.conf /etc/supervisor/conf.d/
CMD ["supervisord", "-c", "/etc/supervisor/supervisord.conf"]